
import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:pdf/pdf.dart';
import 'package:printing/printing.dart';

void main()=>runApp(SkyResumeApp());
class SkyResumeApp extends StatelessWidget{Widget build(BuildContext c)=>MaterialApp(title:'SkyResume',theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.indigo),home:HomeScreen());}
class Resume{String name='Asha Patel',email='asha@example.com',phone='9876543210',summary='Product manager',skills='PM, SQL';String template='clean_minimal';Map toMap()=>{'name':name,'email':email,'phone':phone,'summary':summary,'skills':skills,'template':template};static Resume fromMap(m){var r=Resume();r.name=m['name']??r.name;r.email=m['email']??r.email;r.phone=m['phone']??r.phone;r.summary=m['summary']??r.summary;r.skills=m['skills']??r.skills;r.template=m['template']??r.template;return r;}}
class HomeScreen extends StatefulWidget{_HomeScreenState createState()=>_HomeScreenState();}
class _HomeScreenState extends State<HomeScreen>{Resume r=Resume();bool loading=true;@override void initState(){super.initState();_load();}Future _load()async{final p=await SharedPreferences.getInstance();final s=p.getString('demo');if(s!=null)r=Resume.fromMap(jsonDecode(s));setState(()=>loading=false);}Future _save()async{final p=await SharedPreferences.getInstance();await p.setString('demo',jsonEncode(r.toMap()));ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Saved')));}void _edit(){Navigator.push(context,MaterialPageRoute(builder:(_)=>Editor(resume:r))).then((v){if(v!=null){setState(()=>r=v);_save();}});}void _gallery(){Navigator.push(context,MaterialPageRoute(builder:(_)=>Gallery(selected:r.template))).then((v){if(v!=null){setState(()=>r.template=v);_save();}});}void _preview()async{final bytes=await _buildPdf(r);await Printing.layoutPdf(onLayout:(fmt)async=>bytes);}Future<Uint8List> _buildPdf(Resume s)async{final pdf=pw.Document();pdf.addPage(pw.Page(build:(ctx)=>pw.Center(child:pw.Text(s.name))));return pdf.save();}Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text('SkyResume')),body:loading?Center(child:CircularProgressIndicator()):Padding(padding:EdgeInsets.all(12),child:Column(children:[Row(children:[ElevatedButton.icon(onPressed:_edit,icon:Icon(Icons.edit),label:Text('Edit')),SizedBox(width:8),ElevatedButton.icon(onPressed:_gallery,icon:Icon(Icons.format_paint),label:Text('Templates')),SizedBox(width:8),ElevatedButton.icon(onPressed:_preview,icon:Icon(Icons.picture_as_pdf),label:Text('Preview'))]),SizedBox(height:12),Expanded(child:Center(child:Text('Template: ${r.template}',style:TextStyle(fontSize:18))))])));}
class Editor extends StatefulWidget{final Resume resume;Editor({required this.resume});_EditorState createState()=>_EditorState();}
class _EditorState extends State<Editor>{late Resume r;void initState(){super.initState();r=Resume.fromMap(widget.resume.toMap());}Widget build(BuildContext c){return Scaffold(appBar:AppBar(title:Text('Edit')),body:Padding(padding:EdgeInsets.all(12),child:ListView(children:[TextFormField(initialValue:r.name,decoration:InputDecoration(labelText:'Name'),onChanged:(v)=>r.name=v),SizedBox(height:8),TextFormField(initialValue:r.email,decoration:InputDecoration(labelText:'Email'),onChanged:(v)=>r.email=v),SizedBox(height:8),TextFormField(initialValue:r.phone,decoration:InputDecoration(labelText:'Phone'),onChanged:(v)=>r.phone=v),SizedBox(height:8),TextFormField(initialValue:r.summary,decoration:InputDecoration(labelText:'Summary'),maxLines:4,onChanged:(v)=>r.summary=v),SizedBox(height:8),TextFormField(initialValue:r.skills,decoration:InputDecoration(labelText:'Skills'),onChanged:(v)=>r.skills=v),SizedBox(height:12),ElevatedButton(onPressed:()=>Navigator.pop(context,r),child:Text('Save'))])));}}
class Gallery extends StatelessWidget{final String selected;Gallery({required this.selected});final List<Map<String,String>> t=[{'id':'clean_minimal','name':'Clean Minimal'},{'id':'modern_header','name':'Modern Header'},{'id':'sidebar','name':'Sidebar'},{'id':'two_column','name':'Two Column'},{'id':'bold_top','name':'Bold Top'},{'id':'creative','name':'Creative'},{'id':'simple','name':'Simple'},{'id':'compact','name':'Compact'}];Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text('Templates')),body:GridView.count(crossAxisCount:2,padding:EdgeInsets.all(12),childAspectRatio:3/4,children:t.map((tt)=>GestureDetector(onTap:(){Navigator.pop(c,tt['id']);},child:Card(child:Padding(padding:EdgeInsets.all(8),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(height:120,color:Colors.grey.shade200,child:Center(child:Text(tt['name']!))),SizedBox(height:8),Text(tt['name']!,style:TextStyle(fontWeight:FontWeight.bold)),SizedBox(height:6),Text('Preview')]))))).toList()));}
